name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build playarr-api
      - run: npm run build playarr-ui

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/playarr-api:latest -f apps/playarr-api/Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_USER }}/playarr-ui:latest -f apps/playarr-ui/Dockerfile .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/playarr-api:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/playarr-ui:latest
